import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar/> */}
      {/* <h1>navbar</h1> */}
      <body className={inter.className}>{children}</body>
      {/* <h1>Footer</h1> */}
      {/* <Footer/> */}
    </html>
  );
}
